

# 6.3 异常的处理机制

Java的异常处理机制是如何工作的呢?无论是检查型异常还是非检查型异常，针对可能出现的异常，用户程序必须从以下两种处理方式中做出选择:
**1 )** 在异常出现的方法中主动用try...catch句型处理。
**2)** 如果该方法中没有做出任何处理，就把异常抛给调用该方法的上一层方法，如果上一层方法由try-catch句型处理了，则到此为止，否则继续顺着方法调用的层次逐级向上抛出，沿着被调用的顺序往前寻找，直到找到符合该异常种类的处理程序，交给这部分程序处理，如
果抛到了程序调用顶层，main() 还没有被处理，则程序执行停止，main()  方法发出错误信息。

下图展示了cat() 方法中出现了被零除的异常，该异常在cat()方法里没有得到处理,因此，运行时该异常会被抛给调用cat()的上一级方法pets(),顺着方法调用的层次逐级向上寻找try-catch的处理代码，直到顶层main)方法，此时仍然没有找到匹配的处理程序,程序的执行终止，同时给出错误信息。这种情形可以看作Java在main()程序人口处设置有默认的catch代码块，该代码块的功能是捕获异常，打印错误信息并退出程序。

![在这里插入图片描述](https://raw.githubusercontent.com/yijunquan-afk/img-bed-1/main/img/fd75e482dc1f47228908ab3af466bcfd.png)

## 6.3.1 非检查型异常处理

非检查型异常属于系统定义的运行异常，由系统自动检测并做出默认处理，用户程序不必做任何事情

**举例：处理数组越界出现的异常**

```java
public class TestException_1 {
    //处理数组越界出现的异常
    public static void main(String[] args) {
        int a[]=new int[5];
        a[6]=5;
    }
}
```

运行结果：

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 5
	at com.xjtu.chapter06.TestException_1.main(TestException_1.java:12)
```

**举例：除数为零的异常处理**

```java
public class TestException_2 {
    //除数为零的异常处理
    public static void main(String[] args) {
        int a =0;
        System.out.println(2/a);
    }
}
```

运行结果：

```
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at com.xjtu.chapter06.TestException_2.main(TestException_2.java:11)
```

非检查型异常同样也可以用try-catch句型手工捕获，如下例所示

```java
public class TestException_3 {
    //非检查型异常用try-catch句型处理
    public static void main(String[] args) {
        int[]a=new int[5];
        try{
            a[6]=5;
        }
        catch(ArrayIndexOutOfBoundsException e){
            System.out.println("数组下标越界");
        }
    }
}
```

运行结果：

```
数组下标越界
```



## 6.3.2 检查型异常处理

对于检查型异常，Java要求用户程序必须进行处理，根据具体情况判断在代码段何处处理异常，处理方式包括两种：**捕获异常和声明抛出异常**。对于前者，使用try-catch语句，捕获到发生的异常，并进行相应的处理；对于后者，不在当前方法内处理异常，而是把异常抛出到调用方法中由上层方法处理

### 1、捕获异常

这种处理方式通常是在发生异常的方法内捕获该异常，并立即进行处理，语法格式如下:

```java
try{
    statement()  //可能产生异常的代码块
}catch(exceptiontype objectname){
    statement()  //处理代码块
}
finally{
    statement()  //必须执行的代码
}
```

将可能产生异常的代码块放在try{中，每个try语句必须伴随一个或多个catch语句，用于捕获try 代码块产生的异常并做相应的处理。catch语句可以接受一个参数，即异常类型的对象，exceptiontype必须是一个从Throwable类派生出来的异常类的类型。

有时，需要执行finally语句,finally语句用于执行收尾工作，为异常处理提供一个统一的出口。无论程序是否抛出异常，也无论catch捕获到的异常是否正确，finally 指定的代码都要被执行，并且这个语句总是在方法返回前执行，目的是给程序一个补救的机会。**通常在finally语句中可以清除除了内存以外的其他资源，如关闭打开的文件、删除临时文件等**。

> 注意事项: try、catch、finally三个语句块必须组合起来使用，三者可以组成try...catch...finally、try ...catch和 try..finally三种结构，catch语句可以有一个或多个，**finally语句最多一个**。异常处理的查找遵循类型匹配原则，一个异常在匹配到其中一种异常类型后接着执行catch 块代码，一旦第一个匹配的异常处理被执行，则不会再执行后面的catch块。异常处理执行完毕，程序接着最后一个catch代码段后的语句继续执行。

**举例：为电子商店例子中隐含出错的代码添加异常处理，如果输入的id类型不是整数，则提示报错**

```java
public class Test {
    public static void main(String[] args) {
        Product ipad = new Product();
        BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
        try{
            System.out.println("请输入产品id: ");
            ipad.id = Integer.parseInt(in.readLine());
        }catch (NumberFormatException e){
            System.out.println("id 输入错误，必须输入数字");
            e.printStackTrace();
            System.exit(-1);
        }catch (IOException e){
            System.out.println("标注输入id有误");
            e.printStackTrace();
        }
    }
}
```

此例中的BufferedReader in属于标准I/O输人，**要求必须捕获IOException异常**，否则编译无法通过，因此每一次从键盘输入信息时，in.readLine() 皆需要进行异常捕获。输入产品ID时可能会因输入类型不符合而出现异常，应放人try{}中，随后对输人类型和标准I/O
输人两种异常——NumberFormatException 和lOException进行捕获，当用户输人的产品ID类型不符合要求时，比如输入了字母，则程序终止，并打印错误信息。程序运行示例如下:

```java
请输入产品id: 
ww
id 输入错误，必须输入数字
java.lang.NumberFormatException: For input string: "ww"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.xjtu.chapter06.ex6_1.Test.main(Test.java:18)
```

此例里使用了一个常用的方法printStackTrace)，它是从Throwable类中继承而来的，调用此方法将会打印出“从方法调用处直到异常抛出处”的方法调用序列。捕获异常的顺序会影响到异常的处理，在类层次结构中，一般的异常类型要放在后面，特殊的放在前面。例如，NumberFormatException 要放在Exception前面，否则特殊类型将永远不会被执行。

以上例子中的代码不够完善，如果输入类型不正确，应该可以反复输入，直到输入正确，代码如下：

```java
public class Test_Plus {
    public static void main(String[] args) {
        Product ipad = new Product();
        boolean valid = false;
        BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
        while(!valid){
            try{
                System.out.println("请输入产品id: ");
                ipad.id = Integer.parseInt(in.readLine());
                valid = true;
            }catch (NumberFormatException e){
                System.out.println("id 输入错误，必须输入数字,请重新输入");
            }catch (IOException e){
                System.out.println("标注输入id有误");
                e.printStackTrace();
            }
        }

    }
}
```

运行结果如下：

```
请输入产品id: 
ww
id 输入错误，必须输入数字,请重新输入
请输入产品id: 
e
id 输入错误，必须输入数字,请重新输入
请输入产品id: 
12
```

> <mark>编程提示：</mark>为了程序的稳定性，尽可能全面地考虑到可能出现的异常，不仅要提供错误信息，而且要提供正确的解决方法，保证程序正常运行



### 2、声明抛出异常

在一个方法中生成了异常，但是该方法并不采用try-catch语句处理产生的异常，而是沿着调用层次向上传递，交给调用它的上一层方法来处理，这就是**声明抛出异常**。

声明抛出异常的方法是在产生异常的方法名后面加上关键字throws，后面接上所有可能产生异常的异常类型，语法格式如下:

```{
void func() throws ExceptionA,ExceptionB,ExceptionC{
......
}
```

再用除数为零举例：

```java
public class TestException_4 {
    public static int cat(int x) throws ArithmeticException{
        int z = 10/x;
        return z;
    }

    public static void main(String[] args) {
        int x;
        BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
        try {
            x = Integer.parseInt(in.readLine());
            cat(x);
        }catch (IOException e){
            System.out.println("read error");
        }catch (ArithmeticException e){
            System.out.println("devided by zero");
        }
    }
}
```

这里产生异常时，没有在产生异常的方法里用try-catch语句对异常进行处理，而是抛给了上一层方法