

# 6.4 自定义异常类


原则上，异常处理的过程应该分为三步:首先，将产生异常的代码段放在try{}里，然后抛出(throw)异常，最后捕获(catch) 异常。前面提到的try-catch方式，实际上省略了其中的抛出步骤，try-catch 方式处理的异常通常由Java JVM产生，或者由Java类库中的某些异常类产生，然后隐式地在程序里被抛出，JVM已经替程序完成了抛出异常的操作，而程序中只需执行try和catch两步即可。

然而，有些情形下三个步骤是缺一不可的，例如程序中仅仅使用Java类库提供的异常类不能够满足要求时，**需要自己定义异常类**，当然这些异常JVM是不可能识别的，只能由用户程序手动引发，通过new生成自定义的异常对象，然后将它抛出来(<font color="red">注意:这里是throw而不是throws</font>)。throw 语法格式如下:

```java
throw new ThrowableObject();
```

或者先自定义一个异常类，然后抛出其对象:

```java
myException e = new myException();
throw e;
```

抛出的异常必须是Throwable或其子类的对象，throw语句常用于异常产生语句块中，与try-catch语句配合使用。

**throws与throw仅一个字母的差别，却是两种完全不同的概念。throws写在方法的后面,抛出异常交给上级方法或类，即抛给调用它的方法进一步处理; 而throw多用来抛出自定义的异常类对象，这类异常必须是Throwable类的子类，需要用户自己手工进行捕获。**

首先看看程序中如果显式地将Java类库提供的异常类对象通过throw抛出，这有助于理解异常处理的三个步骤。

举例：使用try，throw，catch处理三种情形：无异常、除数为零、数组越界可能产生的异常

```java
public class Process {
    void Proc(int sel){
        System.out.println("******in case "+sel+" ******");
        if(sel==0){
            //没有异常
            System.out.println("no exception caught");
            return;
        }else if(sel==1){
            try{
                int i=0;
                int j=5/i;//除数为零
                throw new ArithmeticException();//显式地抛出ArithmeticException异常对象
            }catch (ArithmeticException e){
                System.out.println(e.toString());
            }
        }else if(sel==2){
            try{
                int array[] = new int[4];
                array[5]=5;
                throw new ArrayIndexOutOfBoundsException();//显式地抛出ArrayIndexOutOfBoundsExceptionn异常对象
            }catch (ArrayIndexOutOfBoundsException e){
                System.out.println(e.toString());
            }
        }
    }
}

public class Test {
    public static void main(String[] args) {
        Process process = new Process();
        try{
            process.Proc(0);//调用Proc
            process.Proc(1);
            process.Proc(2);
        }catch (ArithmeticException e){
            System.out.println("catch: "+ e+";Reason: "+e.getMessage());
        }catch (ArrayIndexOutOfBoundsException e){
            System.out.println("catch: "+ e+";Reason: "+e.getMessage());
        }catch (Exception e){
            System.out.println("Will not be executed");
        }finally {
            System.out.println("must go inside finally");
        }
    }
}
```

运行结果：

```
******in case 0 ******
no exception caught
******in case 1 ******
java.lang.ArithmeticException: / by zero
******in case 2 ******
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 4
must go inside finally
```

> 此例中一旦有异常产生，就创建异常类ArithmeticException或者ArrayIndexOutOfBoundsException对象，并执行throw new ArithmeticException()语句抛出一个ArithmeticException类异常对象，或者执行throw new ArrayIndexOutOfBoundsException(语句抛出ArrayIndexOutOfBoundsException类异常对象。一 般而言，当抛出Java类库定义的异常时,JVM会自动识别，程序里往往可以省略throw步骤。

如何抛出一个自定义的异常类对象？Java允许用户自行设计异常类，以便处理运行中可能出现的逻辑错误。比如学生年龄为20是-一个整数，如果不小心给学生年龄赋值为200，编译时不会有语法错误，但不符合常识，这时，可以自定义一个AgeException异常类来表示这种异常。在软件开发中，需要自定义异常类的情形有很多,尤其是大型项目开发，开发人员通常预定义好一些异常类，这些异常类可以如同Java类库的异常类一样使用,方便项目组同事共享，在有异常隐患的程序中调用，以提高项目的整体稳定性及协调性。声明自己的异常时，所有异常类都必须是Exception的子类，声明格式如下:

```java
class MyException extends SuperclassOfException{
	...
}
```

其中SuperclassOfException可以为Exception、ArithmeticException、 IOException......

**举例：以电子产品商店为例，假设产品价格少于100元则不合理，自定义一个异常类如下：**

```java
public class PriceException extends Exception {
    public PriceException(){
        System.out.println("the price is less than 100 yuan ,too low!");
    }
}
```

测试类如下：

```java
public class TestPriceException {
    public static void main(String[] args) {
        Product product = new Product();
        product.productPrice = 20;
        try {
            if(product.productPrice<100) throw new PriceException();
        } catch (PriceException e) {
            e.getMessage();
        }

    }
}
```

运行结果如下：

```
the price is less than 100 yuan ,too low!
```


在main()中创建了一个product对象，其价格为20，在try块中判断ProductPrice的价格，小于100，则抛出自定义的PriceException对象，紧跟着的catch语句捕获到对象e后，调用构造方法输出错误信息。

> <mark>编程提示:</mark>程序里尽可能多地使用异常处理机制，在后面的学习中，每一项新内容都应学会使用类库提供的异常处理方法，比如学习JDBC则应学会使用SQLException。

